### ISSUE TITLE
use console.readline

### ISSUE THREAD

**Issue by furesoft** [andrevdm/CSharpConsoleControl#1]
how can i use console.readline?

**Comment by andrevdm** [comment]
Hi Chris,

It has been a **long** time since I last worked on this project. But you would not use Console.ReadLine with this. Rather the control as a `LineEntered` event that you can attach to. If what you are trying to do is block / synchronously wait for a command to be entered, then perhaps doing something with async/await instead would work? (e.g. perhaps something from https://stackoverflow.com/questions/12451609/how-to-await-raising-an-eventhandler-event)

I hope this helps
